<?PHP
$db_host = "127.0.0.1";
$db_name = "DTZ";
$db_username = "root";
$db_password = "";

// Beispiel fuer Aufgaben Variable. Mindestens eine Aufgabe Variable muss existieren
//Bei Debug und File Funktionen wird nur die erste Aufgabe betrachtet
// $aufgaben[] = array("aufgabe_name", "vok_db_name", "anrede_db_name", "schluss_db_name", "bild_pfad");

$aufgaben[] = array("English", "vok_01", "anrede_01", "schluss_01", "img/bild_01.jpg");

?>