<?php

    $_SESSION['testStart'] = time();
	$_SESSION['testEnd'] = $_SESSION['testStart'] + 6000;
	
	$_SESSION['note_S1']=0;
	$_SESSION['note_S2']=0;
	$_SESSION['note_S3']=0;
	$_SESSION['note_S4']=0;
	$_SESSION['note_S5']=0;
	$_SESSION['note_S6']=0;
	$_SESSION['note_S7']=0;
	$_SESSION['note_S8']=0;
	$_SESSION['note_S9']=0;
	$_SESSION['note_S0']=0;
	
	$_SESSION['note_total']=0;

// Fertig
	$_SESSION['fertig_S1']="0";
	$_SESSION['fertig_S2']="0";
	$_SESSION['fertig_S3']="0";
	$_SESSION['fertig_S4']="0";
	$_SESSION['fertig_S5']="0";
	$_SESSION['fertig_S6']="0";
	$_SESSION['fertig_S7']="0";
	$_SESSION['fertig_S8']="0";
	$_SESSION['fertig_S9']="0";
	$_SESSION['fertig_S0']="0";
	
// stores the data

	$_SESSION['tab_S1'] = 0;
	$_SESSION['tab_S2'] = 0;
	$_SESSION['tab_S3'] = 0;
	$_SESSION['tab_S4'] = 0;
	$_SESSION['tab_S5'] = 0;
	$_SESSION['tab_S6'] = 0;
	$_SESSION['tab_S7'] = 0;
	$_SESSION['tab_S8'] = 0;
	$_SESSION['tab_S9'] = 0;
	$_SESSION['tab_S0'] = 0;

?>