<?

	//define("SCRIPTNAME",	"Simple Member");
	define("BASEHREF",	"http://137.250.24.17/DTZ");
	define("DOMAIN",	"localhost");
	define("FROMEMAIL",	"hans-juergen@heringer.net");
	define("SITENAME",	"my_zuwanderer");
	define("INC_DIR",	"/srv/www/htdocs/DTZ/inc/");
	define("PAG_DIR",	INC_DIR."pages/");

	define("INC_DB",	INC_DIR."db.php");

	define("MYSQLUSER",	"admin"); // mysql username
	define("MYSQLPASS",	"serv5daf"); // mysql password
	define("MYSQLDB",	"TAN_DB");    // mysql database name

	require(INC_DB);
?>
